CREATE DOMAIN DM_BLOB_WORD AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80 CHARACTER SET WIN1252;

update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'SITUACAO_PROCESSUAL') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'CONFIRMACAO_PEDIDO_INCLUSAO') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'CONDUTA_UNIDADE_PENAL') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'SERVICO_SOCIAL') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'ENFERMAGEM') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'FARMACIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'CLINICA_MEDICA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'PSIQUIATRIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'ODONTOLOGIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'PSICOLOGIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'TERAPIA_OCUPACIONAL') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'PEDAGOGIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'PROJETO_DEMAIS_ACOES') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'CONCLUSAO') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'INFORMACOES_INTELIGENCIA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'ASSISTENCIA_RELIGIOSA') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'ASSISTENCIA_MATERIAL') and (RDB$RELATION_NAME = 'CTC')  ;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_BLOB_WORD' where (RDB$FIELD_NAME = 'ASSISTENCIA_JURIDICA') and (RDB$RELATION_NAME = 'CTC')  ;

