SET GENERATOR COD_UP TO 110;
COMMIT WORK;

INSERT INTO UNIDADE_PENAL (ID_UP, NOME_UP, ENDERECO, NUMERO, BAIRRO, COMPLEMENTO, CEP, ID_CIDADE, FONE, FAX, CONTATO, FOTO, CAPITAL, REGIAO, SIGLA, REGIME, GENERO, EMAIL, CNPJ) VALUES
(0, 'PENITENCIÁRIA', 'ZONA RURAL', '0', '', NULL, '', NULL, '', '', NULL, NULL, 'S', NULL, 'SIGLA', 'F', 'M', NULL, NULL);

COMMIT WORK;

INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME_FUNCIONARIO, MATRICULA, SENHA, CPF, ID_FUNCAO, LOGIN, ID_UP, PERMISSAO_CONFERE, PERMISSAO_VISITANTE, PERMISSAO_SETORTRABALHO, PERMISSAO_SETOREDUCACAO, CONFIGURACOES, FUNCAO_TEMP, FUNCAO, ADMISSAO, CLASSE, MAE, PAI, RG, ORGAOEMISSOR, FATORRH, ID_NATURALIDADE, DTNASCIMENTO, CARGO, AREA, IMPRIMIR, ENDERECO, BAIRRO, COMPLEMENTO, ID_CIDADE, CEP, FONE, CELULAR, EMAIL, NUMERO, DATA_LOTACAO, ESCOLARIDADE, SEXO, PLANTAO_EXPEDIENTE, NFUNCIONAL, PERMISSAO_CADASTRO, PERMISSAO_PSICOSSOCIAL, PERMISSAO_JURIDICA, PERMISSAO_DISCIPLINA, DIRETORIO_RELATORIO, IDPOSTO_TRABALHO, ID_CURSO, PERMISSAO_CLINICAMEDICA, PERMISSAO_ENFERMAGEM, PERMISSAO_FARMACIA, PERMISSAO_PSIQUIATRIA, PERMISSAO_SERVICOSOCIAL, PERMISSAO_TERAPIAOCUPACIONAL, PERMISSAO_ODONTOLOGIA, PERMISSAO_PEDAGOGIA, PERMISSAO_PSICOLOGIA, PERMISSAO_SAUDE, VISUALIZA_OUTRAS_UP, PERMISSAO_INTELIGENCIA, AUTORIZADO_DELPHI, AUTORIZADO_WEB, SENHA_WEB, PERMISSAO_ARMAS) VALUES
(0, 'ADMIN', NULL, '123', NULL, NULL, 'ADMIN', (SELECT FIRST 1 ID_UP FROM UNIDADE_PENAL), 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', NULL, NULL, NULL, 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'CEDIR', 'S', 'CEDIR', NULL, NULL, NULL, 'CEDIR');

COMMIT WORK;


