insert into artigo (id_artigo, artigo) values (0,'Art. 1º - Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.');
insert into artigo (id_artigo, artigo) values (0,'Art. 2º - Ninguém pode ser punido por fato que lei posterior deixa de considerar crime, cessando em virtude dela a execução e os efeitos penais da sentença condenatória.');
insert into artigo (id_artigo, artigo) values (0,'Art. 3º - A lei excepcional ou temporária, embora decorrido o período de sua duração ou cessadas as circunstâncias que a determinaram, aplica-se ao fato praticado durante sua vigência.');
insert into artigo (id_artigo, artigo) values (0,'Art. 4º - Considera-se praticado o crime no momento da ação ou omissão, ainda que outro seja o momento do resultado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 5º - Aplica-se a lei brasileira, sem prejuízo de convenções, tratados e regras de direito internacional, ao crime cometido no território nacional.');
insert into artigo (id_artigo, artigo) values (0,'Art. 6º - Considera-se praticado o crime no lugar em que ocorreu a ação ou omissão, no todo ou em parte, bem como onde se produziu ou deveria produzir-se o resultado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 7º - Ficam sujeitos à lei brasileira, embora cometidos no estrangeiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 8º - A pena cumprida no estrangeiro atenua a pena imposta no Brasil pelo mesmo crime, quando diversas, ou nela é computada, quando idênticas.');
insert into artigo (id_artigo, artigo) values (0,'Art. 9º - A sentença estrangeira, quando a aplicação da lei brasileira produz na espécie as mesmas conseqüências, pode ser homologada no Brasil para:');
insert into artigo (id_artigo, artigo) values (0,'Art. 10 - O dia do começo inclui-se no cômputo do prazo. Contam-se os dias, os meses e os anos pelo calendário comum.');
insert into artigo (id_artigo, artigo) values (0,'Art. 11 - Desprezam-se, nas penas privativas de liberdade e nas restritivas de direitos, as frações de dia, e, na pena de multa, as frações de cruzeiro.');
insert into artigo (id_artigo, artigo) values (0,'Art. 12 - As regras gerais deste Código aplicam-se aos fatos incriminados por lei especial, se esta não dispuser de modo diverso.');
insert into artigo (id_artigo, artigo) values (0,'Art. 13 - O resultado, de que depende a existência do crime, somente é imputável a quem lhe deu causa. Considera-se causa a ação ou omissão sem a qual o resultado não teria ocorrido.');
insert into artigo (id_artigo, artigo) values (0,'Art. 14 - Diz-se o crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 15 - O agente que, voluntariamente, desiste de prosseguir na execução ou impede que o resultado se produza, só responde pelos atos já praticados.');
insert into artigo (id_artigo, artigo) values (0,'Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços.');
insert into artigo (id_artigo, artigo) values (0,'Art. 17 - Não se pune a tentativa quando, por ineficácia absoluta do meio ou por absoluta impropriedade do objeto, é impossível consumar-se o crime.');
insert into artigo (id_artigo, artigo) values (0,'Art. 18 - Diz-se o crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 19 - Pelo resultado que agrava especialmente a pena, só responde o agente que o houver causado ao menos culposamente.');
insert into artigo (id_artigo, artigo) values (0,'Art. 20 - O erro sobre elemento constitutivo do tipo legal de crime exclui o dolo, mas permite a punição por crime culposo, se previsto em lei.');
insert into artigo (id_artigo, artigo) values (0,'Art. 21 - O desconhecimento da lei é inescusável. O erro sobre a ilicitude do fato, se inevitável, isenta de pena; se evitável, poderá diminuí-la de um sexto a um terço.');
insert into artigo (id_artigo, artigo) values (0,'Art. 22 - Se o fato é cometido sob coação irresistível ou em estrita obediência a ordem, não manifestamente ilegal, de superior hierárquico, só é punível o autor da coação ou da ordem.');
insert into artigo (id_artigo, artigo) values (0,'Art. 23 - Não há crime quando o agente pratica o fato:');
insert into artigo (id_artigo, artigo) values (0,'Art. 24 - Considera-se em estado de necessidade quem pratica o fato para salvar de perigo atual, que não provocou por sua vontade, nem podia de outro modo evitar, direito próprio ou alheio, cujo sacrifício, nas circunstâncias, não era razoável exigir-se.');
insert into artigo (id_artigo, artigo) values (0,'Art. 25 - Entende-se em legítima defesa quem, usando moderadamente dos meios necessários, repele injusta agressão, atual ou iminente, a direito seu ou de outrem.');
insert into artigo (id_artigo, artigo) values (0,'Art. 26 - É isento de pena o agente que, por doença mental ou desenvolvimento mental incompleto ou retardado, era, ao tempo da ação ou da omissão, inteiramente incapaz de entender o caráter ilícito do fato ou de determinar-se de acordo com esse entendimento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 27 - Os menores de 18 (dezoito) anos são penalmente inimputáveis, ficando sujeitos às normas estabelecidas na legislação especial.');
insert into artigo (id_artigo, artigo) values (0,'Art. 28 - Não excluem a imputabilidade penal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 29 - Quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade.');
insert into artigo (id_artigo, artigo) values (0,'Art. 30 - Não se comunicam as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime.');
insert into artigo (id_artigo, artigo) values (0,'Art. 31 - O ajuste, a determinação ou instigação e o auxílio, salvo disposição expressa em contrário, não são puníveis, se o crime não chega, pelo menos, a ser tentado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 32 - As penas são:');
insert into artigo (id_artigo, artigo) values (0,'Art. 33 - A pena de reclusão deve ser cumprida em regime fechado, semi-aberto ou aberto. A de detenção, em regime semi-aberto, ou aberto, salvo necessidade de transferência a regime fechado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 34 - O condenado será submetido, no início do cumprimento da pena, a exame criminológico de classificação para individualização da execução.');
insert into artigo (id_artigo, artigo) values (0,'Art. 35 - Aplica-se a norma do art. 34 deste Código, caput, ao condenado que inicie o cumprimento da pena em regime semi-aberto.');
insert into artigo (id_artigo, artigo) values (0,'Art. 36 - O regime aberto baseia-se na autodisciplina e senso de responsabilidade do condenado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 37 - As mulheres cumprem pena em estabelecimento próprio, observando-se os deveres e direitos inerentes à sua condição pessoal, bem como, no que couber, o disposto neste Capítulo.');
insert into artigo (id_artigo, artigo) values (0,'Art. 38 - O preso conserva todos os direitos não atingidos pela perda da liberdade, impondo-se a todas as autoridades o respeito à sua integridade física e moral.');
insert into artigo (id_artigo, artigo) values (0,'Art. 39 - O trabalho do preso será sempre remunerado, sendo-lhe garantidos os benefícios da Previdência Social.');
insert into artigo (id_artigo, artigo) values (0,'Art. 40 - A legislação especial regulará a matéria prevista nos arts. 38 e 39 deste Código, bem como especificará os deveres e direitos do preso, os critérios para revogação e transferência dos regimes e estabelecerá as infrações disciplinares e correspondentes sanções.');
insert into artigo (id_artigo, artigo) values (0,'Art. 41 - O condenado a quem sobrevém doença mental deve ser recolhido a hospital de custódia e tratamento psiquiátrico ou, à falta, a outro estabelecimento adequado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 42 - Computam-se, na pena privativa de liberdade e na medida de segurança, o tempo de prisão provisória, no Brasil ou no estrangeiro, o de prisão administrativa e o de internação em qualquer dos estabelecimentos referidos no artigo anterior.');
insert into artigo (id_artigo, artigo) values (0,'Art. 43 - As penas restritivas de direitos são:');
insert into artigo (id_artigo, artigo) values (0,'Art. 44 - As penas restritivas de direitos são autônomas e substituem as privativas de liberdade, quando:');
insert into artigo (id_artigo, artigo) values (0,'Art. 45 - A pena restritiva de direitos converte-se em privativa de liberdade, pelo tempo da pena aplicada, quando:');
insert into artigo (id_artigo, artigo) values (0,'Art. 46 - A prestação de serviços à comunidade consiste na atribuição ao condenado de tarefas gratuitas junto a entidades assistenciais, hospitais, escolas, orfanatos e outros estabelecimentos congêneres, em programas comunitários ou estatais.');
insert into artigo (id_artigo, artigo) values (0,'Art. 47 - As penas de interdição temporária de direitos são:');
insert into artigo (id_artigo, artigo) values (0,'Art. 48 - A limitação de fim de semana consiste na obrigação de permanecer, aos sábados e domingos, por 5 (cinco) horas diárias, em casa de albergado ou outro estabelecimento adequado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 49 - A pena de multa consiste no pagamento ao fundo penitenciário da quantia fixada na sentença e calculada em dias-multa. Será, no mínimo, de 10 (dez) e, no máximo, de 360 (trezentos e sessenta) dias-multa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 50 - A multa deve ser paga dentro de 10 (dez) dias depois de transitada em julgado a sentença. A requerimento do condenado e conforme as circunstâncias, o juiz pode permitir que o pagamento se realize em parcelas mensais.');
insert into artigo (id_artigo, artigo) values (0,'Art. 51 - Transitada em julgado a sentença condenatória, a multa será considerada dívida de valor, aplicando-se-lhes as normas da legislação relativa à dívida ativa da Fazenda Pública, inclusive no que concerne às causas interruptivas e suspensivas da prescrição.');
insert into artigo (id_artigo, artigo) values (0,'Art. 52 - É suspensa a execução da pena de multa, se sobrevém ao condenado doença mental.');
insert into artigo (id_artigo, artigo) values (0,'Art. 53 - As penas privativas de liberdade têm seus limites estabelecidos na sanção correspondente a cada tipo legal de crime.');
insert into artigo (id_artigo, artigo) values (0,'Art. 54 - As penas restritivas de direitos são aplicáveis, independentemente de cominação na parte especial, em substituição à pena privativa de liberdade, fixada em quantidade inferior a 1 (um) ano, ou nos crimes culposos.');
insert into artigo (id_artigo, artigo) values (0,'Art. 55 - As penas restritivas de direitos terão a mesma duração da pena privativa de liberdade substituída.');
insert into artigo (id_artigo, artigo) values (0,'Art. 56 - As penas de interdição, previstas nos incisos I e II do art. 47 deste Código, aplicam-se para todo o crime cometido no exercício de profissão, atividade, ofício, cargo ou função, sempre que houver violação dos deveres que lhes são inerentes.');
insert into artigo (id_artigo, artigo) values (0,'Art. 57 - A pena de interdição, prevista no inciso III do art. 47 deste Código, aplica-se aos crimes culposos de trânsito.');
insert into artigo (id_artigo, artigo) values (0,'Art. 58 - A multa, prevista em cada tipo legal de crime, tem os limites fixados no art. 49 e seus parágrafos deste Código.');
insert into artigo (id_artigo, artigo) values (0,'Art. 59 - O juiz, atendendo à culpabilidade, aos antecedentes, à conduta social, à personalidade do agente, aos motivos, às circunstâncias e conseqüências do crime, bem como ao comportamento da vítima, estabelecerá, conforme seja necessário e suficiente para reprovação e prevenção do crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 60 - Na fixação da pena de multa o juiz deve atender, principalmente, à situação econômica do réu.');
insert into artigo (id_artigo, artigo) values (0,'Art. 61 - São circunstâncias que sempre agravam a pena, quando não constituem ou qualificam o crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 62 - A pena será ainda agravada em relação ao agente que:');
insert into artigo (id_artigo, artigo) values (0,'Art. 63 - Verifica-se a reincidência quando o agente comete novo crime, depois de transitar em julgado a sentença que, no País ou no estrangeiro, o tenha condenado por crime anterior.');
insert into artigo (id_artigo, artigo) values (0,'Art. 64 - Para efeito de reincidência:');
insert into artigo (id_artigo, artigo) values (0,'Art. 65 - São circunstâncias que sempre atenuam a pena:');
insert into artigo (id_artigo, artigo) values (0,'Art. 66 - A pena poderá ser ainda atenuada em razão de circunstância relevante, anterior ou posterior ao crime, embora não prevista expressamente em lei.');
insert into artigo (id_artigo, artigo) values (0,'Art. 67 - No concurso de agravantes e atenuantes, a pena deve aproximar-se do limite indicado pelas circunstâncias preponderantes, entendendo-se como tais as que resultam dos motivos determinantes do crime, da personalidade do agente e da reincidência.');
insert into artigo (id_artigo, artigo) values (0,'Art. 68 - A pena-base será fixada atendendo-se ao critério do art. 59 deste Código; em seguida serão consideradas as circunstâncias atenuantes e agravantes; por último, as causas de diminuição e de aumento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 69 - Quando o agente, mediante mais de uma ação ou omissão, pratica dois ou mais crimes, idênticos ou não, aplicam-se cumulativamente as penas privativas de liberdade em que haja incorrido. No caso de aplicação cumulativa de penas de reclusão e de detenção, executa-se primeiro aquela.');
insert into artigo (id_artigo, artigo) values (0,'Art. 70 - Quando o agente, mediante uma só ação ou omissão, pratica dois ou mais crimes, idênticos ou não, aplica-se-lhe a mais grave das penas cabíveis ou, se iguais, somente uma delas, mas aumentada, em qualquer caso, de um sexto até metade. As penas aplicam-se, entretanto, cumulativamente, se a ação ou omissão é dolosa e os crimes concorrentes resultam de desígnios autônomos, consoante o disposto no artigo anterior.');
insert into artigo (id_artigo, artigo) values (0,'Art. 71 - Quando o agente, mediante mais de uma ação ou omissão, pratica dois ou mais crimes da mesma espécie e, pelas condições de tempo, lugar, maneira de execução e outras semelhantes, devem os subseqüentes ser havidos como continuação do primeiro, aplica-se-lhe a pena de um só dos crimes, se idênticas, ou a mais grave, se diversas, aumentada, em qualquer caso, de um sexto a dois terços.');
insert into artigo (id_artigo, artigo) values (0,'Art. 72 - No concurso de crimes, as penas de multa são aplicadas distinta e integralmente.');
insert into artigo (id_artigo, artigo) values (0,'Art. 73 - Quando, por acidente ou erro no uso dos meios de execução, o agente, ao invés de atingir a pessoa que pretendia ofender, atinge pessoa diversa, responde como se tivesse praticado o crime contra aquela, atendendo-se ao disposto no § 3º do art. 20 deste Código. No caso de ser também atingida a pessoa que o agente pretendia ofender, aplica-se a regra do art. 70 deste Código.');
insert into artigo (id_artigo, artigo) values (0,'Art. 74 - Fora dos casos do artigo anterior, quando, por acidente ou erro na execução do crime, sobrevém resultado diverso do pretendido, o agente responde por culpa, se o fato é previsto como crime culposo; se ocorre também o resultado pretendido, aplica-se a regra do art. 70 deste Código.');
insert into artigo (id_artigo, artigo) values (0,'Art. 75 - O tempo de cumprimento das penas privativas de liberdade não pode ser superior a 30 (trinta) anos.');
insert into artigo (id_artigo, artigo) values (0,'Art. 76 - No concurso de infrações, executar-se-á primeiramente a pena mais grave.');
insert into artigo (id_artigo, artigo) values (0,'Art. 77 - A execução da pena privativa de liberdade, não superior a 2 (dois) anos, poderá ser suspensa, por 2 (dois) a 4 (quatro) anos, desde que:');
insert into artigo (id_artigo, artigo) values (0,'Art. 78 - Durante o prazo da suspensão, o condenado ficará sujeito à observação e ao cumprimento das condições estabelecidas pelo juiz.');
insert into artigo (id_artigo, artigo) values (0,'Art. 79 - A sentença poderá especificar outras condições a que fica subordinada a suspensão, desde que adequadas ao fato e à situação pessoal do condenado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 80 - A suspensão não se estende às penas restritivas de direitos nem à multa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 81 - A suspensão será revogada se, no curso do prazo, o beneficiário:');
insert into artigo (id_artigo, artigo) values (0,'Art. 82 - Expirado o prazo sem que tenha havido revogação, considera-se extinta a pena privativa de liberdade.');
insert into artigo (id_artigo, artigo) values (0,'Art. 83 - O juiz poderá conceder livramento condicional ao condenado a pena privativa de liberdade igual ou superior a 2 (dois) anos, desde que:');
insert into artigo (id_artigo, artigo) values (0,'Art. 84 - As penas que correspondem a infrações diversas devem somar-se para efeito do livramento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 85 - A sentença especificará as condições a que fica subordinado o livramento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 86 - Revoga-se o livramento, se o liberado vem a ser condenado a pena privativa de liberdade, em sentença irrecorrível:');
insert into artigo (id_artigo, artigo) values (0,'Art. 87 - O juiz poderá, também, revogar o livramento, se o liberado deixar de cumprir qualquer das obrigações constantes da sentença, ou for irrecorrivelmente condenado, por crime ou contravenção, a pena que não seja privativa de liberdade.');
insert into artigo (id_artigo, artigo) values (0,'Art. 88 - Revogado o livramento, não poderá ser novamente concedido, e, salvo quando a revogação resulta de condenação por outro crime anterior àquele benefício, não se desconta na pena o tempo em que esteve solto o condenado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 89 - O juiz não poderá declarar extinta a pena, enquanto não passar em julgado a sentença em processo a que responde o liberado, por crime cometido na vigência do livramento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 90 - Se até o seu término o livramento não é revogado, considera-se extinta a pena privativa de liberdade.');
insert into artigo (id_artigo, artigo) values (0,'Art. 91 - São efeitos da condenação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 92 - São também efeitos da condenação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 93 - A reabilitação alcança quaisquer penas aplicadas em sentença definitiva, assegurando ao condenado o sigilo dos registros sobre o seu processo e condenação.');
insert into artigo (id_artigo, artigo) values (0,'Art. 94 - A reabilitação poderá ser requerida, decorridos 2 (dois) anos do dia em que for extinta, de qualquer modo, a pena ou terminar sua execução, computando-se o período de prova da suspensão e o do livramento condicional, se não sobrevier revogação, desde que o condenado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 95 - A reabilitação será revogada, de ofício ou a requerimento do Ministério Público, se o reabilitado for condenado, como reincidente, por decisão definitiva, a pena que não seja de multa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 96. As medidas de segurança são:');
insert into artigo (id_artigo, artigo) values (0,'Art. 97 - Se o agente for inimputável, o juiz determinará sua internação (art. 26). Se, todavia, o fato previsto como crime for punível com detenção, poderá o juiz submetê-lo a tratamento ambulatorial.');
insert into artigo (id_artigo, artigo) values (0,'Art. 98 - Na hipótese do parágrafo único do art. 26 deste Código e necessitando o condenado de especial tratamento curativo, a pena privativa de liberdade pode ser substituída pela internação, ou tratamento ambulatorial, pelo prazo mínimo de 1 (um) a 3 (três) anos, nos termos do artigo anterior e respectivos §§ 1º a 4º.');
insert into artigo (id_artigo, artigo) values (0,'Art. 99 - O internado será recolhido a estabelecimento dotado de características hospitalares e será submetido a tratamento.');
insert into artigo (id_artigo, artigo) values (0,'Art. 100 - A ação penal é pública, salvo quando a lei expressamente a declara privativa do ofendido.');
insert into artigo (id_artigo, artigo) values (0,'Art. 101 - Quando a lei considera como elemento ou circunstâncias do tipo legal fatos que, por si mesmos, constituem crimes, cabe ação pública em relação àquele, desde que, em relação a qualquer destes, se deva proceder por iniciativa do Ministério Público.');
insert into artigo (id_artigo, artigo) values (0,'Art. 102 - A representação será irretratável depois de oferecida a denúncia.');
insert into artigo (id_artigo, artigo) values (0,'Art. 103 - Salvo disposição expressa em contrário, o ofendido decai do direito de queixa ou de representação se não o exerce dentro do prazo de 6 (seis) meses, contado do dia em que veio a saber quem é o autor do crime, ou, no caso do § 3º do art. 100 deste Código, do dia em que se esgota o prazo para oferecimento da denúncia.');
insert into artigo (id_artigo, artigo) values (0,'Art. 104 - O direito de queixa não pode ser exercido quando renunciado expressa ou tacitamente.');
insert into artigo (id_artigo, artigo) values (0,'Art. 105 - O perdão do ofendido, nos crimes em que somente se procede mediante queixa, obsta ao prosseguimento da ação.');
insert into artigo (id_artigo, artigo) values (0,'Art. 106 - O perdão, no processo ou fora dele, expresso ou tácito:');
insert into artigo (id_artigo, artigo) values (0,'Art. 107 - Extingue-se a punibilidade:');
insert into artigo (id_artigo, artigo) values (0,'Art. 108 - A extinção da punibilidade de crime que é pressuposto, elemento constitutivo ou circunstância agravante de outro não se estende a este. Nos crimes conexos, a extinção da punibilidade de um deles não impede, quanto aos outros, a agravação da pena resultante da conexão.');
insert into artigo (id_artigo, artigo) values (0,'Art. 109 - A prescrição, antes de transitar em julgado a sentença final, salvo o disposto nos §§ 1º e 2º do art. 110 deste Código, regula-se pelo máximo da pena privativa de liberdade cominada ao crime, verificando-se:');
insert into artigo (id_artigo, artigo) values (0,'Art. 110 - A prescrição depois de transitar em julgado a sentença condenatória regula-se pela pena aplicada e verifica-se nos prazos fixados no artigo anterior, os quais se aumentam de um terço, se o condenado é reincidente.');
insert into artigo (id_artigo, artigo) values (0,'Art. 111 - A prescrição, antes de transitar em julgado a sentença final, começa a correr:');
insert into artigo (id_artigo, artigo) values (0,'Art. 112 - No caso do art. 110 deste Código, a prescrição começa a correr:');
insert into artigo (id_artigo, artigo) values (0,'Art. 113 - No caso de evadir-se o condenado ou de revogar-se o livramento condicional, a prescrição é regulada pelo tempo que resta da pena.');
insert into artigo (id_artigo, artigo) values (0,'Art. 114 - A prescrição da pena de multa ocorrerá:');
insert into artigo (id_artigo, artigo) values (0,'Art. 115 - São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença, maior de 70 (setenta) anos.');
insert into artigo (id_artigo, artigo) values (0,'Art. 116 - Antes de passar em julgado a sentença final, a prescrição não corre:');
insert into artigo (id_artigo, artigo) values (0,'Art. 117 - O curso da prescrição interrompe-se:');
insert into artigo (id_artigo, artigo) values (0,'Art. 118 - As penas mais leves prescrevem com as mais graves.');
insert into artigo (id_artigo, artigo) values (0,'Art. 119 - No caso de concurso de crimes, a extinção da punibilidade incidirá sobre a pena de cada um, isoladamente.');
insert into artigo (id_artigo, artigo) values (0,'Art. 120 - A sentença que conceder perdão judicial não será considerada para efeitos de reincidência.');
insert into artigo (id_artigo, artigo) values (0,'Art. 121 - Matar alguém:');
insert into artigo (id_artigo, artigo) values (0,'Art. 122 - Induzir ou instigar alguém a suicidar-se ou prestar-lhe auxílio para que o faça:');
insert into artigo (id_artigo, artigo) values (0,'Art. 123 - Matar, sob a influência do estado puerperal, o próprio filho, durante o parto ou logo após:');
insert into artigo (id_artigo, artigo) values (0,'Art. 124 - Provocar aborto em si mesma ou consentir que outrem lho provoque:');
insert into artigo (id_artigo, artigo) values (0,'Art. 125 - Provocar aborto, sem o consentimento da gestante:');
insert into artigo (id_artigo, artigo) values (0,'Art. 126 - Provocar aborto com o consentimento da gestante:');
insert into artigo (id_artigo, artigo) values (0,'Art. 127 - As penas cominadas nos dois artigos anteriores são aumentadas de um terço, se, em conseqüência do aborto ou dos meios empregados para provocá-lo, a gestante sofre lesão corporal de natureza grave; e são duplicadas, se, por qualquer dessas causas, lhe sobrevém a morte.');
insert into artigo (id_artigo, artigo) values (0,'Art. 128 - Não se pune o aborto praticado por médico:');
insert into artigo (id_artigo, artigo) values (0,'Art. 129 - Ofender a integridade corporal ou a saúde de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 130 - Expor alguém, por meio de relações sexuais ou qualquer ato libidinoso, a contágio de moléstia venérea, de que sabe ou deve saber que está contaminado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 131 - Praticar, com o fim de transmitir a outrem moléstia grave de que está contaminado, ato capaz de produzir o contágio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 132 - Expor a vida ou a saúde de outrem a perigo direto e iminente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 133 - Abandonar pessoa que está sob seu cuidado, guarda, vigilância ou autoridade, e, por qualquer motivo, incapaz de defender-se dos riscos resultantes do abandono:');
insert into artigo (id_artigo, artigo) values (0,'Art. 134 - Expor ou abandonar recém-nascido, para ocultar desonra própria:');
insert into artigo (id_artigo, artigo) values (0,'Art. 135 - Deixar de prestar assistência, quando possível fazê-lo sem risco pessoal, à criança abandonada ou extraviada, ou à pessoa inválida ou ferida, ao desamparo ou em grave e iminente perigo; ou não pedir, nesses casos, o socorro da autoridade pública:');
insert into artigo (id_artigo, artigo) values (0,'Art. 136 - Expor a perigo a vida ou a saúde de pessoa sob sua autoridade, guarda ou vigilância, para fim de educação, ensino, tratamento ou custódia, quer privando-a de alimentação ou cuidados indispensáveis, quer sujeitando-a a trabalho excessivo ou inadequado, quer abusando de meios de correção ou disciplina:');
insert into artigo (id_artigo, artigo) values (0,'Art. 137 - Participar de rixa, salvo para separar os contendores:');
insert into artigo (id_artigo, artigo) values (0,'Art. 138 - Caluniar alguém, imputando-lhe falsamente fato definido como crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 139 - Difamar alguém, imputando-lhe fato ofensivo à sua reputação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 140 - Injuriar alguém, ofendendo-lhe a dignidade ou o decoro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 141 - As penas cominadas neste Capítulo aumentam-se de um terço, se qualquer dos crimes é cometido:');
insert into artigo (id_artigo, artigo) values (0,'Art. 142 - Não constituem injúria ou difamação punível:');
insert into artigo (id_artigo, artigo) values (0,'Art. 143 - O querelado que, antes da sentença, se retrata cabalmente da calúnia ou da difamação, fica isento de pena.');
insert into artigo (id_artigo, artigo) values (0,'Art. 144 - Se, de referências, alusões ou frases, se infere calúnia, difamação ou injúria, quem se julga ofendido pode pedir explicações em juízo. Aquele que se recusa a dá-las ou, a critério do juiz, não as dá satisfatórias, responde pela ofensa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 145 - Nos crimes previstos neste Capítulo somente se procede mediante queixa, salvo quando, no caso do art. 140, § 2º, da violência resulta lesão corporal.');
insert into artigo (id_artigo, artigo) values (0,'Art. 146 - Constranger alguém, mediante violência ou grave ameaça, ou depois de lhe haver reduzido, por qualquer outro meio, a capacidade de resistência, a não fazer o que a lei permite, ou a fazer o que ela não manda:');
insert into artigo (id_artigo, artigo) values (0,'Art. 147 - Ameaçar alguém, por palavra, escrito ou gesto, ou qualquer outro meio simbólico, de causar-lhe mal injusto e grave:');
insert into artigo (id_artigo, artigo) values (0,'Art. 148 - Privar alguém de sua liberdade, mediante seqüestro ou cárcere privado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 149 - Reduzir alguém a condição análoga à de escravo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 150 - Entrar ou permanecer, clandestina ou astuciosamente, ou contra a vontade expressa ou tácita de quem de direito, em casa alheia ou em suas dependências:');
insert into artigo (id_artigo, artigo) values (0,'Art. 151 - Devassar indevidamente o conteúdo de correspondência fechada, dirigida a outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 152 - Abusar da condição de sócio ou empregado de estabelecimento comercial ou industrial para, no todo ou em parte, desviar, sonegar, subtrair ou suprimir correspondência, ou revelar a estranho seu conteúdo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 153 - Divulgar alguém, sem justa causa, conteúdo de documento particular ou de correspondência confidencial, de que é destinatário ou detentor, e cuja divulgação possa produzir dano a outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 154 - Revelar alguém, sem justa causa, segredo, de que tem ciência em razão de função, ministério, ofício ou profissão, e cuja revelação possa produzir dano a outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 155 - Subtrair, para si ou para outrem, coisa alheia móvel:');
insert into artigo (id_artigo, artigo) values (0,'Art. 156 - Subtrair o condômino, co-herdeiro ou sócio, para si ou para outrem, a quem legitimamente a detém, a coisa comum:');
insert into artigo (id_artigo, artigo) values (0,'Art. 157 - Subtrair coisa móvel alheia, para si ou para outrem, mediante grave ameaça ou violência a pessoa, ou depois de havê-la, por qualquer meio, reduzido à impossibilidade de resistência:');
insert into artigo (id_artigo, artigo) values (0,'Art. 158 - Constranger alguém, mediante violência ou grave ameaça, e com o intuito de obter para si ou para outrem indevida vantagem econômica, a fazer, tolerar que se faça ou deixar fazer alguma coisa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 159 - Seqüestrar pessoa com o fim de obter, para si ou para outrem, qualquer vantagem, como condição ou preço do resgate:');
insert into artigo (id_artigo, artigo) values (0,'Art. 160 - Exigir ou receber, como garantia de dívida, abusando da situação de alguém, documento que pode dar causa a procedimento criminal contra a vítima ou contra terceiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 161 - Suprimir ou deslocar tapume, marco, ou qualquer outro sinal indicativo de linha divisória, para apropriar-se, no todo ou em parte, de coisa imóvel alheia:');
insert into artigo (id_artigo, artigo) values (0,'Art. 162 - Suprimir ou alterar, indevidamente, em gado ou rebanho alheio, marca ou sinal indicativo de propriedade:');
insert into artigo (id_artigo, artigo) values (0,'Art. 163 - Destruir, inutilizar ou deteriorar coisa alheia:');
insert into artigo (id_artigo, artigo) values (0,'Art. 164 - Introduzir ou deixar animais em propriedade alheia, sem consentimento de quem de direito, desde que o fato resulte prejuízo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 165 - Destruir, inutilizar ou deteriorar coisa tombada pela autoridade competente em virtude de valor artístico, arqueológico ou histórico:');
insert into artigo (id_artigo, artigo) values (0,'Art. 166 - Alterar, sem licença da autoridade competente, o aspecto de local especialmente protegido por lei:');
insert into artigo (id_artigo, artigo) values (0,'Art. 167 - Nos casos do art. 163, do inciso IV do seu parágrafo e do art. 164, somente se procede mediante queixa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 168 - Apropriar-se de coisa alheia móvel, de que tem a posse ou a detenção:');
insert into artigo (id_artigo, artigo) values (0,'Art. 169 - Apropriar-se alguém de coisa alheia vinda ao seu poder por erro, caso fortuito ou força da natureza:');
insert into artigo (id_artigo, artigo) values (0,'Art. 170 - Nos crimes previstos neste Capítulo, aplica-se o disposto no art. 155, § 2º.');
insert into artigo (id_artigo, artigo) values (0,'Art. 171 - Obter, para si ou para outrem, vantagem ilícita, em prejuízo alheio, induzindo ou mantendo alguém em erro, mediante artifício, ardil, ou qualquer outro meio fraudulento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 172 - Emitir fatura, duplicata ou nota de venda que não corresponda à mercadoria vendida, em quantidade ou qualidade, ou ao serviço prestado.');
insert into artigo (id_artigo, artigo) values (0,'Art. 173 - Abusar, em proveito próprio ou alheio, de necessidade, paixão ou inexperiência de menor, ou da alienação ou debilidade mental de outrem, induzindo qualquer deles à prática de ato suscetível de produzir efeito jurídico, em prejuízo próprio ou de terceiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 174 - Abusar, em proveito próprio ou alheio, da inexperiência ou da simplicidade ou inferioridade mental de outrem, induzindo-o à prática de jogo ou aposta, ou à especulação com títulos ou mercadorias, sabendo ou devendo saber que a operação é ruinosa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 175 - Enganar, no exercício de atividade comercial, o adquirente ou consumidor:');
insert into artigo (id_artigo, artigo) values (0,'Art. 176 - Tomar refeição em restaurante, alojar-se em hotel ou utilizar-se de meio de transporte sem dispor de recursos para efetuar o pagamento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 177 - Promover a fundação de sociedade por ações, fazendo, em prospecto ou em comunicação ao público ou à assembléia, afirmação falsa sobre a constituição da sociedade, ou ocultando fraudulentamente fato a ela relativo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 178 - Emitir conhecimento de depósito ou warrant, em desacordo com disposição legal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 179 - Fraudar execução, alienando, desviando, destruindo ou danificando bens, ou simulando dívidas:');
insert into artigo (id_artigo, artigo) values (0,'Art. 180 - Adquirir, receber ou ocultar, em proveito próprio ou alheio, coisa que sabe ser produto de crime, ou influir para que terceiro, de boa-fé, a adquira, receba ou oculte:');
insert into artigo (id_artigo, artigo) values (0,'Art. 181 - É isento de pena quem comete qualquer dos crimes previstos neste título, em prejuízo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 182 - Somente se procede mediante representação, se o crime previsto neste título é cometido em prejuízo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 183 - Não se aplica o disposto nos dois artigos anteriores:');
insert into artigo (id_artigo, artigo) values (0,'Art. 184 - Violar direito autoral:');
insert into artigo (id_artigo, artigo) values (0,'Art. 185 - Atribuir falsamente a alguém, mediante o uso de nome, pseudônimo ou sinal por ele adotado para designar seus trabalhos, a autoria de obra literária, científica ou artística:');
insert into artigo (id_artigo, artigo) values (0,'Art. 186 - Nos crimes previstos neste Capítulo somente se procede mediante queixa, salvo quando praticados em prejuízo de entidade de direito público, autarquia, empresa pública, sociedade de economia mista ou fundação instituída pelo poder público, e nos casos previstos nos §§ 1º e 2º do art. 184 desta Lei.');
insert into artigo (id_artigo, artigo) values (0,'Art. 187 - Violar direito de privilégio de invenção ou de descoberta:');
insert into artigo (id_artigo, artigo) values (0,'Art. 188 - Exercer, como privilegiada, indústria que não o seja, ou depois de anulado, suspenso ou caduco o privilégio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 189 - Reproduzir, por qualquer meio, no todo ou em parte, sem autorização, desenho ou modelo de privilégio alheio; explorar, sem autorização, desenho ou modelo de privilégio alheio; vender, expor à venda ou introduzir no país objeto que é imitação ou cópia de modelo privilegiado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 190 - Usar em modelo ou desenho, de expressão que o dê falsamente como depositado, ou mencionar em anúncio ou papel comercial, como depositado, desenho ou modelo que não o seja:');
insert into artigo (id_artigo, artigo) values (0,'Art. 191 - Nos crimes previstos neste Capítulo, excetuados os dos arts. 188, e o seu parágrafo, e 190, somente se procede mediante queixa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 192 - Violar direito de marca de indústria ou de comércio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 193 - Reproduzir, sem autorização, no todo ou em parte, ou imitar de modo que possa induzir em erro ou confusão, armas, brasões ou distintivos públicos, nacionais ou estrangeiros, em marca de indústria ou comércio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 194 - Usar, em produto ou artigo, marca que indique procedência que não é a verdadeira, ou vender ou expor à venda produto ou artigo, com essa marca:');
insert into artigo (id_artigo, artigo) values (0,'Art. 195 - Nos crimes previstos neste Capítulo, salvo os dos arts. 193, e seu parágrafo, e 194, somente se procede mediante queixa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 196 - Fazer concorrência desleal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 197 - Constranger alguém, mediante violência ou grave ameaça:');
insert into artigo (id_artigo, artigo) values (0,'Art. 198 - Constranger alguém, mediante violência ou grave ameaça, a celebrar contrato de trabalho, ou a não fornecer a outrem ou não adquirir de outrem matéria-prima ou produto industrial ou agrícola:');
insert into artigo (id_artigo, artigo) values (0,'Art. 199 - Constranger alguém, mediante violência ou grave ameaça, a participar ou deixar de participar de determinado sindicato ou associação profissional:');
insert into artigo (id_artigo, artigo) values (0,'Art. 200 - Participar de suspensão ou abandono coletivo de trabalho, praticando violência contra pessoa ou contra coisa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 201 - Participar de suspensão ou abandono coletivo de trabalho, provocando a interrupção de obra pública ou serviço de interesse coletivo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 202 - Invadir ou ocupar estabelecimento industrial, comercial ou agrícola, com o intuito de impedir ou embaraçar o curso normal do trabalho, ou com o mesmo fim danificar o estabelecimento ou as coisas nele existentes ou delas dispor:');
insert into artigo (id_artigo, artigo) values (0,'Art. 203 - Frustrar, mediante fraude ou violência, direito assegurado pela legislação do trabalho:');
insert into artigo (id_artigo, artigo) values (0,'Art. 204 - Frustrar, mediante fraude ou violência, obrigação legal relativa à nacionalização do trabalho:');
insert into artigo (id_artigo, artigo) values (0,'Art. 205 - Exercer atividade, de que está impedido por decisão administrativa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 206 - Recrutar trabalhadores, mediante fraude, com o fim de levá-los para território estrangeiro.');
insert into artigo (id_artigo, artigo) values (0,'Art. 207 - Aliciar trabalhadores, com o fim de levá-los de uma para outra localidade do território nacional:');
insert into artigo (id_artigo, artigo) values (0,'Art. 208 - Escarnecer de alguém publicamente, por motivo de crença ou função religiosa; impedir ou perturbar cerimônia ou prática de culto religioso; vilipendiar publicamente ato ou objeto de culto religioso:');
insert into artigo (id_artigo, artigo) values (0,'Art. 209 - Impedir ou perturbar enterro ou cerimônia funerária:');
insert into artigo (id_artigo, artigo) values (0,'Art. 210 - Violar ou profanar sepultura ou urna funerária:');
insert into artigo (id_artigo, artigo) values (0,'Art. 211 - Destruir, subtrair ou ocultar cadáver ou parte dele:');
insert into artigo (id_artigo, artigo) values (0,'Art. 212 - Vilipendiar cadáver ou suas cinzas:');
insert into artigo (id_artigo, artigo) values (0,'Art. 213 - Constranger mulher à conjunção carnal, mediante violência ou grave ameaça:');
insert into artigo (id_artigo, artigo) values (0,'Art. 214 - Constranger alguém, mediante violência ou grave ameaça, a praticar ou permitir que com ele se pratique ato libidinoso diverso da conjunção carnal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 215 - Ter conjunção carnal com mulher honesta, mediante fraude:');
insert into artigo (id_artigo, artigo) values (0,'Art. 216 - Induzir mulher honesta, mediante fraude, a praticar ou permitir que com ela se pratique ato libidinoso diverso da conjunção carnal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 217 - Seduzir mulher virgem, menor de 18 (dezoito) anos e maior de 14 (catorze), e ter com ela conjunção carnal, aproveitando-se de sua inexperiência ou justificável confiança:');
insert into artigo (id_artigo, artigo) values (0,'Art. 218 - Corromper ou facilitar a corrupção de pessoa maior de 14 (catorze) e menor de 18 (dezoito) anos, com ela praticando ato de libidinagem, ou induzindo-a a praticá-lo ou presenciá-lo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 219 - Raptar mulher honesta, mediante violência, grave ameaça ou fraude, para fim libidinoso:');
insert into artigo (id_artigo, artigo) values (0,'Art. 220 - Se a raptada é maior de 14 (catorze) anos e menor de 21 (vinte e um), e o rapto se dá com seu consentimento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 221 - É diminuída de um terço a pena, se o rapto é para fim de casamento, e de metade, se o agente, sem ter praticado com a vítima qualquer ato libidinoso, a restitue à liberdade ou a coloca em lugar seguro, à disposição da família.');
insert into artigo (id_artigo, artigo) values (0,'Art. 222 - Se o agente, ao efetuar o rapto, ou em seguida a este, pratica outro crime contra a raptada, aplicam-se cumulativamente a pena correspondente ao rapto e a cominada ao outro crime.');
insert into artigo (id_artigo, artigo) values (0,'Art. 223 - Se da violência resulta lesão corporal de natureza grave:');
insert into artigo (id_artigo, artigo) values (0,'Art. 224 - Presume-se a violência, se a vítima:');
insert into artigo (id_artigo, artigo) values (0,'Art. 225 - Nos crimes definidos nos capítulos anteriores, somente se procede mediante queixa.');
insert into artigo (id_artigo, artigo) values (0,'Art. 226 - A pena é aumentada de quarta parte:');
insert into artigo (id_artigo, artigo) values (0,'Art. 227 - Induzir alguém a satisfazer a lascívia de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 228 - Induzir ou atrair alguém à prostituição, facilitá-la ou impedir que alguém a abandone:');
insert into artigo (id_artigo, artigo) values (0,'Art. 229 - Manter, por conta própria ou de terceiro, casa de prostituição ou lugar destinado a encontros para fim libidinoso, haja, ou não, intuito de lucro ou mediação direta do proprietário ou gerente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 230 - Tirar proveito da prostituição alheia, participando diretamente de seus lucros ou fazendo-se sustentar, no todo ou em parte, por quem a exerça:');
insert into artigo (id_artigo, artigo) values (0,'Art. 231 - Promover ou facilitar a entrada, no território nacional, de mulher que nele venha exercer a prostituição, ou a saída de mulher que vá exercê-la no estrangeiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 232 - Nos crimes de que trata este Capítulo, é aplicável o disposto nos arts. 223 e 224.');
insert into artigo (id_artigo, artigo) values (0,'Art. 233 - Praticar ato obsceno em lugar público, ou aberto ou exposto ao público:');
insert into artigo (id_artigo, artigo) values (0,'Art. 234 - Fazer, importar, exportar, adquirir ou ter sob sua guarda, para fim de comércio, de distribuição ou de exposição pública, escrito, desenho, pintura, estampa ou qualquer objeto obsceno:');
insert into artigo (id_artigo, artigo) values (0,'Art. 235 - Contrair alguém, sendo casado, novo casamento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 236 - Contrair casamento, induzindo em erro essencial o outro contraente, ou ocultando-lhe impedimento que não seja casamento anterior:');
insert into artigo (id_artigo, artigo) values (0,'Art. 237 - Contrair casamento, conhecendo a existência de impedimento que lhe cause a nulidade absoluta:');
insert into artigo (id_artigo, artigo) values (0,'Art. 238 - Atribuir-se falsamente autoridade para celebração de casamento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 239 - Simular casamento mediante engano de outra pessoa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 240 - Cometer adultério:');
insert into artigo (id_artigo, artigo) values (0,'Art. 241 - Promover no registro civil a inscrição de nascimento inexistente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 242 - Dar parto alheio como próprio; registrar como seu o filho de outrem; ocultar recém-nascido ou substituí-lo, suprimindo ou alterando direito inerente ao estado civil:');
insert into artigo (id_artigo, artigo) values (0,'Art. 243 - Deixar em asilo de expostos ou outra instituição de assistência filho próprio ou alheio, ocultando-lhe a filiação ou atribuindo-lhe outra, com o fim de prejudicar direito inerente ao estado civil:');
insert into artigo (id_artigo, artigo) values (0,'Art. 244 - Deixar, sem justa causa, de prover a subsistência do cônjuge, ou de filho menor de 18 (dezoito) anos ou inapto para o trabalho, ou de ascendente inválido ou valetudinário, não lhes proporcionando os recursos necessários ou faltando ao pagamento de pensão alimentícia judicialmente acordada, fixada ou majorada; deixar, sem justa causa, de socorrer descendente ou ascendente, gravemente enfermo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 245 - Entregar filho menor de 18 (dezoito) anos a pessoa em cuja companhia saiba ou deva saber que o menor fica moral ou materialmente em perigo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 246 - Deixar, sem justa causa, de prover à instrução primária de filho em idade escolar:');
insert into artigo (id_artigo, artigo) values (0,'Art. 247 - Permitir alguém que menor de 18 (dezoito) anos, sujeito a seu poder ou confiado à sua guarda ou vigilância:');
insert into artigo (id_artigo, artigo) values (0,'Art. 248 - Induzir menor de 18 (dezoito) anos, ou interdito, a fugir do lugar em que se acha por determinação de quem sobre ele exerce autoridade, em virtude de lei ou de ordem judicial; confiar a outrem sem ordem do pai, do tutor ou do curador algum menor de 18 (dezoito) anos ou interdito, ou deixar, sem justa causa, de entregá-lo a quem legitimamente o reclame:');
insert into artigo (id_artigo, artigo) values (0,'Art. 249 - Subtrair menor de 18 (dezoito) anos ou interdito ao poder de quem o tem sob sua guarda em virtude de lei ou de ordem judicial:');
insert into artigo (id_artigo, artigo) values (0,'Art. 250 - Causar incêndio, expondo a perigo a vida, a integridade física ou o patrimônio de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 251 - Expor a perigo a vida, a integridade física ou o patrimônio de outrem, mediante explosão, arremesso ou simples colocação de engenho de dinamite ou de substância de efeitos análogos:');
insert into artigo (id_artigo, artigo) values (0,'Art. 252 - Expor a perigo a vida, a integridade física ou o patrimônio de outrem, usando de gás tóxico ou asfixiante:');
insert into artigo (id_artigo, artigo) values (0,'Art. 253 - Fabricar, fornecer, adquirir, possuir ou transportar, sem licença da autoridade, substância ou engenho explosivo, gás tóxico ou asfixiante, ou material destinado à sua fabricação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 254 - Causar inundação, expondo a perigo a vida, a integridade física ou o patrimônio de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 255 - Remover, destruir ou inutilizar, em prédio próprio ou alheio, expondo a perigo a vida, a integridade física ou o patrimônio de outrem, obstáculo natural ou obra destinada a impedir inundação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 256 - Causar desabamento ou desmoronamento, expondo a perigo a vida, a integridade física ou o patrimônio de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 257 - Subtrair, ocultar ou inutilizar, por ocasião de incêndio, inundação, naufrágio, ou outro desastre ou calamidade, aparelho, material ou qualquer meio destinado a serviço de combate ao perigo, de socorro ou salvamento; ou impedir ou dificultar serviço de tal natureza:');
insert into artigo (id_artigo, artigo) values (0,'Art. 258 - Se do crime doloso de perigo comum resulta lesão corporal de natureza grave, a pena privativa de liberdade é aumentada de metade; se resulta morte, é aplicada em dobro. No caso de culpa, se do fato resulta lesão corporal, a pena aumenta-se de metade; se resulta morte, aplica-se a pena cominada ao homicídio culposo, aumentada de um terço.');
insert into artigo (id_artigo, artigo) values (0,'Art. 259 - Difundir doença ou praga que possa causar dano a floresta, plantação ou animais de utilidade econômica:');
insert into artigo (id_artigo, artigo) values (0,'Art. 260 - Impedir ou perturbar serviço de estrada de ferro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 261 - Expor a perigo embarcação ou aeronave, própria ou alheia, ou praticar qualquer ato tendente a impedir ou dificultar navegação marítima, fluvial ou aérea:');
insert into artigo (id_artigo, artigo) values (0,'Art. 262 - Expor a perigo outro meio de transporte público, impedir-lhe ou dificultar-lhe o funcionamento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 263 - Se de qualquer dos crimes previstos nos arts. 260 a 262, no caso de desastre ou sinistro, resulta lesão corporal ou morte, aplica-se o disposto no art. 258.');
insert into artigo (id_artigo, artigo) values (0,'Art. 264 - Arremessar projétil contra veículo, em movimento, destinado ao transporte público por terra, por água ou pelo ar:');
insert into artigo (id_artigo, artigo) values (0,'Art. 265 - Atentar contra a segurança ou o funcionamento de serviço de água, luz, força ou calor, ou qualquer outro de utilidade pública:');
insert into artigo (id_artigo, artigo) values (0,'Art. 266 - Interromper ou perturbar serviço telegráfico, radiotelegráfico ou telefônico, impedir ou dificultar-lhe o restabelecimento:');
insert into artigo (id_artigo, artigo) values (0,'Art. 267 - Causar epidemia, mediante a propagação de germes patogênicos:');
insert into artigo (id_artigo, artigo) values (0,'Art. 268 - Infringir determinação do poder público, destinada a impedir introdução ou propagação de doença contagiosa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 269 - Deixar o médico de denunciar à autoridade pública doença cuja notificação é compulsória:');
insert into artigo (id_artigo, artigo) values (0,'Art. 270 - Envenenar água potável, de uso comum ou particular, ou substância alimentícia ou medicinal destinada a consumo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 271 - Corromper ou poluir água potável, de uso comum ou particular, tornando-a imprópria para consumo ou nociva à saúde:');
insert into artigo (id_artigo, artigo) values (0,'Art. 272 - Corromper, adulterar ou falsificar substância alimentícia ou medicinal destinada a consumo, tornando-a nociva à saúde:');
insert into artigo (id_artigo, artigo) values (0,'Art. 273 - Alterar substância alimentícia ou medicinal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 274 - Empregar, no fabrico de produto destinado a consumo, revestimento, gaseificação artificial, matéria corante, substância aromática, anti-séptica, conservadora ou qualquer outra não expressamente permitida pela legislação sanitária:');
insert into artigo (id_artigo, artigo) values (0,'Art. 275 - Inculcar, em invólucro ou recipiente de produto alimentício ou medicinal, a existência de substância que não se encontra em seu conteúdo ou que nele existe em quantidade menor que a mencionada:');
insert into artigo (id_artigo, artigo) values (0,'Art. 276 - Vender, expor à venda, ter em depósito para vender ou, de qualquer forma, entregar a consumo produto nas condições dos arts. 274 e 275.');
insert into artigo (id_artigo, artigo) values (0,'Art. 277 - Vender, expor à venda, ter em depósito ou ceder substância destinada à falsificação de produto alimentício ou medicinal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 278 - Fabricar, vender, expor à venda, ter em depósito para vender ou, de qualquer forma, entregar a consumo coisa ou substância nociva à saúde, ainda que não destinada à alimentação ou a fim medicinal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 279 - (Revogado pela Lei nº 8.137, de 27-12-1990.)');
insert into artigo (id_artigo, artigo) values (0,'Art. 280 - Fornecer substância medicinal em desacordo com receita médica:');
insert into artigo (id_artigo, artigo) values (0,'Art. 281 - (Revogado pela Lei nº 6.368, de 21-10-1976).');
insert into artigo (id_artigo, artigo) values (0,'Art. 282 - Exercer, ainda que a título gratuito, a profissão de médico, dentista ou farmacêutico, sem autorização legal ou excedendo-lhe os limites:');
insert into artigo (id_artigo, artigo) values (0,'Art. 283 - Inculcar ou anunciar cura por meio secreto ou infalível:');
insert into artigo (id_artigo, artigo) values (0,'Art. 284 - Exercer o curandeirismo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 285 - Aplica-se o disposto no art. 258 aos crimes previstos neste Capítulo, salvo quanto ao definido no art. 267.');
insert into artigo (id_artigo, artigo) values (0,'Art. 286 - Incitar, publicamente, a prática de crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 287 - Fazer, publicamente, apologia de fato criminoso ou de autor de crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 288 - Associarem-se mais de três pessoas, em quadrilha ou bando, para o fim de cometer crimes:');
insert into artigo (id_artigo, artigo) values (0,'Art. 289 - Falsificar, fabricando-a ou alterando-a, moeda metálica ou papel-moeda de curso legal no país ou no estrangeiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 290 - Formar cédula, nota ou bilhete representativo de moeda com fragmentos de cédulas, notas ou bilhetes verdadeiros; suprimir, em nota, cédula ou bilhete recolhidos, para o fim de restituí-los à circulação, sinal indicativo de sua inutilização; restituir à circulação cédula, nota ou bilhete em tais condições, ou já recolhidos para o fim de inutilização:');
insert into artigo (id_artigo, artigo) values (0,'Art. 291 - Fabricar, adquirir, fornecer, a título oneroso ou gratuito, possuir ou guardar maquinismo, aparelho, instrumento ou qualquer objeto especialmente destinado à falsificação de moeda:');
insert into artigo (id_artigo, artigo) values (0,'Art. 292 - Emitir, sem permissão legal, nota, bilhete, ficha, vale ou título que contenha promessa de pagamento em dinheiro ao portador ou a que falte indicação do nome da pessoa a quem deva ser pago:');
insert into artigo (id_artigo, artigo) values (0,'Art. 293 - Falsificar, fabricando-os ou alterando-os:');
insert into artigo (id_artigo, artigo) values (0,'Art. 294 - Fabricar, adquirir, fornecer, possuir ou guardar objeto especialmente destinado à falsificação de qualquer dos papéis referidos no artigo anterior:');
insert into artigo (id_artigo, artigo) values (0,'Art. 295 - Se o agente é funcionário público, e comete o crime prevalecendo-se do cargo, aumenta-se a pena de sexta parte.');
insert into artigo (id_artigo, artigo) values (0,'Art. 296 - Falsificar, fabricando-os ou alterando-os:');
insert into artigo (id_artigo, artigo) values (0,'Art. 297 - Falsificar, no todo ou em parte, documento público, ou alterar documento público verdadeiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 298 - Falsificar, no todo ou em parte, documento particular ou alterar documento particular verdadeiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 299 - Omitir, em documento público ou particular, declaração que dele devia constar, ou nele inserir ou fazer inserir declaração falsa ou diversa da que devia ser escrita, com o fim de prejudicar direito, criar obrigação ou alterar a verdade sobre fato juridicamente relevante:');
insert into artigo (id_artigo, artigo) values (0,'Art. 300 - Reconhecer, como verdadeira, no exercício de função pública, firma ou letra que o não seja:');
insert into artigo (id_artigo, artigo) values (0,'Art. 301 - Atestar ou certificar falsamente, em razão de função pública, fato ou circunstância que habilite alguém a obter cargo público, isenção de ônus ou de serviço de caráter público, ou qualquer outra vantagem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 302 - Dar o médico, no exercício da sua profissão, atestado falso:');
insert into artigo (id_artigo, artigo) values (0,'Art. 303 - Reproduzir ou alterar selo ou peça filatélica que tenha valor para coleção, salvo quando a reprodução ou a alteração está visivelmente anotada na face ou no verso do selo ou peça:');
insert into artigo (id_artigo, artigo) values (0,'Art. 304 - Fazer uso de qualquer dos papéis falsificados ou alterados, a que se referem os arts. 297 a 302:');
insert into artigo (id_artigo, artigo) values (0,'Art. 305 - Destruir, suprimir ou ocultar, em benefício próprio ou de outrem, ou em prejuízo alheio, documento público ou particular verdadeiro, de que não podia dispor:');
insert into artigo (id_artigo, artigo) values (0,'Art. 306 - Falsificar, fabricando-o ou alterando-o, marca ou sinal empregado pelo poder público no contraste de metal precioso ou na fiscalização alfandegária, ou usar marca ou sinal dessa natureza, falsificado por outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 307 - Atribuir-se ou atribuir a terceiro falsa identidade para obter vantagem, em proveito próprio ou alheio, ou para causar dano a outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 308 - Usar, como próprio, passaporte, título de eleitor, caderneta de reservista ou qualquer documento de identidade alheia ou ceder a outrem, para que dele se utilize, documento dessa natureza, próprio ou de terceiro:');
insert into artigo (id_artigo, artigo) values (0,'Art. 309 - Usar o estrangeiro, para entrar ou permanecer no território nacional, nome que não é o seu:');
insert into artigo (id_artigo, artigo) values (0,'Art. 310 - Atribuir a estrangeiro falsa qualidade, para promover-lhe a entrada em território nacional:');
insert into artigo (id_artigo, artigo) values (0,'Art. 311 - Prestar-se a figurar como proprietário ou possuidor de ação, título ou valor pertencente a estrangeiro, nos casos em que a este é vedada por lei a propriedade ou a posse de tais bens:');
insert into artigo (id_artigo, artigo) values (0,'Art. 312 - Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo, ou desviá-lo, em proveito próprio ou alheio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 313 - Apropriar-se de dinheiro ou qualquer utilidade que, no exercício do cargo, recebeu por erro de outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 314 - Extraviar livro oficial ou qualquer documento, de que tem a guarda em razão do cargo; sonegá-lo ou inutilizá-lo, total ou parcialmente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 315 - Dar às verbas ou rendas públicas aplicação diversa da estabelecida em lei:');
insert into artigo (id_artigo, artigo) values (0,'Art. 316 - Exigir, para si ou para outrem, direta ou indiretamente, ainda que fora da função ou antes de assumi-la, mas em razão dela, vantagem indevida:');
insert into artigo (id_artigo, artigo) values (0,'Art. 317 - Solicitar ou receber, para si ou para outrem, direta ou indiretamente, ainda que fora da função ou antes de assumi-la, mas em razão dela, vantagem indevida, ou aceitar promessa de tal vantagem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 318 - Facilitar, com infração de dever funcional, a prática de contrabando ou descaminho (art. 334):');
insert into artigo (id_artigo, artigo) values (0,'Art. 319 - Retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal:');
insert into artigo (id_artigo, artigo) values (0,'Art. 320 - Deixar o funcionário, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo ou, quando lhe falte competência, não levar o fato ao conhecimento da autoridade competente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 321 - Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário:');
insert into artigo (id_artigo, artigo) values (0,'Art. 322 - Praticar violência, no exercício de função ou a pretexto de exercê-la:');
insert into artigo (id_artigo, artigo) values (0,'Art. 323 - Abandonar cargo público, fora dos casos permitidos em lei:');
insert into artigo (id_artigo, artigo) values (0,'Art. 324 - Entrar no exercício de função pública antes de satisfeitas as exigências legais, ou continuar a exercê-la, sem autorização, depois de saber oficialmente que foi exonerado, removido, substituído ou suspenso:');
insert into artigo (id_artigo, artigo) values (0,'Art. 325 - Revelar fato de que tem ciência em razão do cargo e que deva permanecer em segredo, ou facilitar-lhe a revelação:');
insert into artigo (id_artigo, artigo) values (0,'Art. 326 - Devassar o sigilo de proposta de concorrência pública, ou proporcionar a terceiro o ensejo de devassá-lo:');
insert into artigo (id_artigo, artigo) values (0,'Art. 327 - Considera-se funcionário público, para os efeitos penais, quem, embora transitoriamente ou sem remuneração, exerce cargo, emprego ou função pública.');
insert into artigo (id_artigo, artigo) values (0,'Art. 328 - Usurpar o exercício de função pública:');
insert into artigo (id_artigo, artigo) values (0,'Art. 329 - Opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio:');
insert into artigo (id_artigo, artigo) values (0,'Art. 330 - Desobedecer a ordem legal de funcionário público:');
insert into artigo (id_artigo, artigo) values (0,'Art. 331 - Desacatar funcionário público no exercício da função ou em razão dela:');
insert into artigo (id_artigo, artigo) values (0,'Art. 332 - Solicitar, exigir, cobrar ou obter, para si ou para outrem, vantagem ou promessa de vantagem, a pretexto de influir em ato praticado por funcionário público no exercício da função:');
insert into artigo (id_artigo, artigo) values (0,'Art. 333 - Oferecer ou prometer vantagem indevida a funcionário público, para determiná-lo a praticar, omitir ou retardar ato de ofício:');
insert into artigo (id_artigo, artigo) values (0,'Art. 334 - Importar ou exportar mercadoria proibida ou iludir, no todo ou em parte, o pagamento de direito ou imposto devido pela entrada, pela saída ou pelo consumo de mercadoria:');
insert into artigo (id_artigo, artigo) values (0,'Art. 335 - Impedir, perturbar ou fraudar concorrência pública ou venda em hasta pública, promovida pela administração federal, estadual ou municipal, ou por entidade paraestatal; afastar ou procurar afastar concorrente ou licitante, por meio de violência, grave ameaça, fraude ou oferecimento de vantagem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 336 - Rasgar ou, de qualquer forma, inutilizar ou conspurcar edital afixado por ordem de funcionário público; violar ou inutilizar selo ou sinal empregado, por determinação legal ou por ordem de funcionário público, para identificar ou cerrar qualquer objeto:');
insert into artigo (id_artigo, artigo) values (0,'Art. 337 - Subtrair, ou inutilizar, total ou parcialmente, livro oficial, processo ou documento confiado à custódia de funcionário, em razão de ofício, ou de particular em serviço público:');
insert into artigo (id_artigo, artigo) values (0,'Art. 338 - Reingressar no território nacional o estrangeiro que dele foi expulso:');
insert into artigo (id_artigo, artigo) values (0,'Art. 339 - Dar causa a instauração de investigação policial ou de processo judicial contra alguém, imputando-lhe crime de que o sabe inocente:');
insert into artigo (id_artigo, artigo) values (0,'Art. 340 - Provocar a ação de autoridade, comunicando-lhe a ocorrência de crime ou de contravenção que sabe não se ter verificado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 341 - Acusar-se, perante a autoridade, de crime inexistente ou praticado por outrem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 342 - Fazer afirmação falsa, ou negar ou calar a verdade, como testemunha, perito, tradutor ou intérprete em processo judicial, policial ou administrativo, ou em juízo arbitral:');
insert into artigo (id_artigo, artigo) values (0,'Art. 343 - Dar, oferecer, ou prometer dinheiro ou qualquer outra vantagem a testemunha, perito, tradutor ou intérprete, para fazer afirmação falsa, negar ou calar a verdade em depoimento, perícia, tradução ou interpretação, ainda que a oferta ou promessa não seja aceita:');
insert into artigo (id_artigo, artigo) values (0,'Art. 344 - Usar de violência ou grave ameaça, com o fim de favorecer interesse próprio ou alheio, contra autoridade, parte, ou qualquer outra pessoa que funciona ou é chamada a intervir em processo judicial, policial ou administrativo, ou em juízo arbitral:');
insert into artigo (id_artigo, artigo) values (0,'Art. 345 - Fazer justiça pelas próprias mãos, para satisfazer pretensão, embora legítima, salvo quando a lei o permite:');
insert into artigo (id_artigo, artigo) values (0,'Art. 346 - Tirar, suprimir, destruir ou danificar coisa própria, que se acha em poder de terceiro por determinação judicial ou convenção:');
insert into artigo (id_artigo, artigo) values (0,'Art. 347 - Inovar artificiosamente, na pendência de processo civil ou administrativo, o estado de lugar, de coisa ou de pessoa, com o fim de induzir a erro o juiz ou o perito:');
insert into artigo (id_artigo, artigo) values (0,'Art. 348 - Auxiliar a subtrair-se à ação de autoridade pública autor de crime a que é cominada pena de reclusão:');
insert into artigo (id_artigo, artigo) values (0,'Art. 349 - Prestar a criminoso, fora dos casos de co-autoria ou de receptação, auxílio destinado a tornar seguro o proveito do crime:');
insert into artigo (id_artigo, artigo) values (0,'Art. 350 - Ordenar ou executar medida privativa de liberdade individual, sem as formalidades legais ou com abuso de poder:');
insert into artigo (id_artigo, artigo) values (0,'Art. 351 - Promover ou facilitar a fuga de pessoa legalmente presa ou submetida a medida de segurança detentiva:');
insert into artigo (id_artigo, artigo) values (0,'Art. 352 - Evadir-se ou tentar evadir-se o preso ou o indivíduo submetido a medida de segurança detentiva, usando de violência contra a pessoa:');
insert into artigo (id_artigo, artigo) values (0,'Art. 353 - Arrebatar preso, a fim de maltratá-lo, do poder de quem o tenha sob custódia ou guarda:');
insert into artigo (id_artigo, artigo) values (0,'Art. 354 - Amotinarem-se presos, perturbando a ordem ou disciplina da prisão:');
insert into artigo (id_artigo, artigo) values (0,'Art. 355 - Trair, na qualidade de advogado ou procurador, o dever profissional, prejudicando interesse, cujo patrocínio, em juízo, lhe é confiado:');
insert into artigo (id_artigo, artigo) values (0,'Art. 356 - Inutilizar, total ou parcialmente, ou deixar de restituir autos, documento ou objeto de valor probatório, que recebeu na qualidade de advogado ou procurador:');
insert into artigo (id_artigo, artigo) values (0,'Art. 357 - Solicitar ou receber dinheiro ou qualquer outra utilidade, a pretexto de influir em juiz, jurado, órgão do Ministério Público, funcionário de justiça, perito, tradutor, intérprete ou testemunha:');
insert into artigo (id_artigo, artigo) values (0,'Art. 358 - Impedir, perturbar ou fraudar arrematação judicial; afastar ou procurar afastar concorrente ou licitante, por meio de violência, grave ameaça, fraude ou oferecimento de vantagem:');
insert into artigo (id_artigo, artigo) values (0,'Art. 359 - Exercer função, atividade, direito, autoridade ou múnus, de que foi suspenso ou privado por decisão judicial:');
insert into artigo (id_artigo, artigo) values (0,'Art. 360 - Ressalvada a legislação especial sobre os crimes contra a existência, a segurança e a integridade do Estado e contra a guarda e o emprego da economia popular, os crimes de imprensa e os de falência, os de responsabilidade do Presidente da República e dos Governadores ou Interventores, e os crimes militares, revogam-se as disposições em contrário.');
insert into artigo (id_artigo, artigo) values (0,'Art. 361 - Este Código entrará em vigor no dia 1º de janeiro de 1942.');


